### ISSUE TITLE
Caption is not good

### ISSUE THREAD

**Issue by Tdannen** [QuantLet/Collaboration_Example_MVAghadatail#2]
dots have no label

**Comment by polarstern** [comment]
done, images should be updated
![mvaghadatail_1-1](https://cloud.githubusercontent.com/assets/14127572/9856293/0d61d57e-5b14-11e5-8879-eab8578901da.png)
![mvaghadatail_2-1](https://cloud.githubusercontent.com/assets/14127572/9856292/0d61313c-5b14-11e5-950e-030972f692c7.png)

**Comment by Tdannen** [comment]
looks perfect
